/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 63
#define YY_END_OF_BUFFER 64
static yyconst short int yy_accept[378] =
    {   0,
        0,    0,   64,   61,    2,    1,    2,   60,   25,   10,
        4,   11,   14,   14,   14,   14,   24,   60,   60,   60,
       60,    8,   12,    9,    3,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,    6,
        7,   61,    2,    2,   60,    0,    0,    0,   14,   60,
       14,   14,   14,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,    5,    0,    0,    0,    0,
       13,   14,   14,   60,   60,   60,   60,   60,   60,   60,

       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,    0,    0,
        0,   13,   14,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   20,   42,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   39,   35,
       60,   58,   60,   32,   60,   34,   60,   60,   60,   15,
       60,    0,    0,    0,    0,   60,   60,   60,   60,   60,
       60,   60,   60,   30,   60,   43,   60,   60,   60,   60,
       60,   60,   16,   60,   60,   60,   60,   60,   60,   60,

       60,   60,   60,   18,   60,    0,    0,    0,    0,   60,
       60,   49,   60,   60,   60,   60,   38,   60,   31,   60,
       60,   60,   60,   54,    0,    0,   60,   60,   60,   37,
       60,   60,   60,   60,   60,    0,    0,    0,    0,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
        0,    0,    0,    0,   60,   60,   60,    0,   21,   60,
       51,   60,   57,    0,   23,    0,    0,    0,   50,   60,
       60,   60,   60,   60,   19,   60,   60,   60,   26,    0,
        0,    0,    0,   60,   60,   60,    0,   60,   60,    0,
        0,    0,    0,    0,    0,    0,   48,   47,   60,   60,

       60,   60,   29,   41,    0,   56,    0,    0,   28,   60,
        0,    0,   53,   60,    0,    0,    0,    0,   22,   60,
       60,   60,   60,    0,    0,    0,   60,    0,    0,   60,
        0,   60,   60,   46,   60,    0,    0,    0,   17,    0,
        0,   60,   62,   60,   60,   60,    0,   55,    0,    0,
        0,   60,   60,   60,   36,    0,   59,    0,    0,   60,
       60,   60,    0,    0,   27,   60,   44,   45,    0,    0,
       60,    0,   33,   40,    0,   52,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    1,    1,    1,    1,
        1,    1,    1,    8,    9,   10,   11,   12,   13,   14,
       15,   16,   16,   16,   16,   16,   17,   18,    7,    7,
        7,    7,   19,    7,   19,   20,   19,   21,   19,   19,
       19,   19,   19,   19,   19,   19,   22,   19,   19,   23,
       19,   19,   19,   19,   24,   19,   19,   25,   19,   19,
       26,   27,   28,    7,   29,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   45,   19,   46,   47,   48,   49,   50,   19,   19,
       51,   19,   52,    1,   53,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        5,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   54,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        5,    1,    1,    5,   55,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[56] =
    {   0,
        1,    2,    2,    2,    2,    3,    3,    2,    1,    4,
        3,    4,    4,    4,    4,    4,    4,    3,    4,    4,
        4,    4,    4,    4,    4,    3,    3,    3,    3,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[381] =
    {   0,
        0,    0,  652, 1133,   54,   57,   60,   63,   55,   71,
       63, 1133,   91,  631,  634,    0, 1133,   79,   81,   83,
       85, 1133, 1133, 1133, 1133,   93,  112,  114,  118,  125,
       95,  120,  128,  131,  133,  116,  138,  142,  167, 1133,
     1133,  585,  169,  175,  154,  168,  589,  578,  179,  190,
        0,  196,  202,  195,  218,  220,  223,  225,  228,  231,
      233,  235,  237,  241,  239,  243,  245,  248,  253,  250,
      255,  258,  262,  268,  276,  284,  288,  297,  299,  302,
      304,  306,  310,  313,  317, 1133,  314,  577,  556,  334,
      342,  352,  358,  330,  374,  321,  376,  378,  381,  383,

      385,  387,  389,  391,  319,  393,  395,  397,  399,  401,
      403,  410,  423,  337,  428,  430,  432,  434,  439,  442,
      444,  447,  451,  456,  459,  464,  466,  468,  489,  584,
      538,  495,  563,  480,  473,  475,  485,  487,  491,  493,
      514,  519,  521,  526,  528,  530,  535,  339,  532,  537,
      539,  541,  543,  545,  548,  554,  557,  559,  563,  566,
      577,  579,  583,  585,  587,  589,  592,  594,  596,  598,
      603,  554,  543,  106,  595,  607,  609,  611,  613,  615,
      622,  617,  627,  629,  631,  633,  640,  642,  648,  653,
      657,  663,  660,  665,  667,  673,  675,  679,  682,  684,

      686,  689,  695,  697,  699,  696,  541,  697,  708,  721,
      726,  728,  730,  732,  734,  736,  739,  742,  744,  747,
      749,  751,  753,  755,  425,  516,  758,  761,  763,  770,
      767,  776,  783,  786,  788,  788,  780,  126,  517,  806,
      808,  810,  815,  818,  812,  823,  826,  830,  832,  834,
      474,  461,  441,  443,  836,  838,  841,  439,  843,  848,
      852,  855,  857,  446, 1133,  179,  855,  850,  867,  869,
      875,  880,  883,  887,  891,  893,  895,  897,  900,  408,
      396,  382,  380,  902,  905,  911,  372,  914,  916,  908,
      243,  918,  935,  918,  941,  930,  957,  960,  963,  965,

      967,  969,  971,  973,  362, 1133,  375,  300,  975,  977,
      306,  289,  979,  981,  972, 1001,  978, 1014, 1133,  991,
      994,  996, 1000,  271,  272,  255, 1002,  252,  235, 1005,
      269, 1020, 1030, 1007, 1032,  243,  219,  229, 1036,  183,
      190, 1038, 1133, 1041, 1043, 1048,  116, 1133,  120,  119,
      100, 1050, 1052, 1054, 1056,  113, 1133,   98,   96, 1060,
     1062, 1065,   80,   75, 1133, 1068, 1071, 1075,   64,   53,
     1078,   47, 1133, 1080,   46, 1133, 1133, 1124, 1126, 1128
    } ;

static yyconst short int yy_def[381] =
    {   0,
      377,    1,  377,  377,  377,  377,  378,  378,  377,  378,
      377,  377,  378,   13,   13,   13,  377,  378,  378,  378,
      378,  377,  377,  377,  377,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  377,
      377,  377,  377,  378,  378,  377,  377,  377,  377,   13,
       13,   13,   13,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  377,  377,  377,  377,  377,
       13,   13,   13,  378,  378,  378,  378,  378,  378,  378,

      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  377,  377,
      377,  377,   13,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  377,  377,  377,  377,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,

      378,  378,  378,  378,  378,  377,  377,  377,  377,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  377,  377,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  377,  377,  379,  377,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      377,  377,  377,  377,  378,  378,  378,  377,  378,  378,
      378,  378,  378,  377,  377,  379,  380,  377,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  377,
      377,  377,  377,  378,  378,  378,  377,  378,  378,  377,
      380,  380,  380,  377,  377,  377,  378,  378,  378,  378,

      378,  378,  378,  378,  377,  377,  377,  377,  378,  378,
      377,  377,  378,  378,  377,  377,  377,  380,  377,  378,
      378,  378,  378,  377,  377,  377,  378,  377,  377,  378,
      377,  378,  378,  378,  378,  377,  377,  377,  378,  377,
      377,  378,  377,  378,  378,  378,  377,  377,  377,  377,
      377,  378,  378,  378,  378,  377,  377,  377,  377,  378,
      378,  378,  377,  377,  377,  378,  378,  378,  377,  377,
      378,  377,  377,  378,  377,  377,    0,  377,  377,  377
    } ;

static yyconst short int yy_nxt[1189] =
    {   0,
        4,    5,    6,    7,    8,    9,    4,   10,   11,    8,
       12,   13,   14,   15,   16,   16,   16,   17,    8,    8,
       18,   19,   20,   21,    8,   22,   23,   24,   25,   26,
        8,   27,   28,   29,   30,    8,    8,   31,   32,    8,
       33,    8,   34,   35,   36,    8,   37,   38,    8,   39,
        8,   40,   41,    4,   42,   43,   43,   43,   43,   43,
       43,   43,   43,   44,  377,  377,   46,   46,   46,   46,
       46,   46,  377,  377,   49,   49,   49,   49,   49,   49,
      377,  377,  377,  377,  377,  377,  377,  377,  376,   47,
      375,   48,  377,  377,  377,  377,  377,  377,   54,  373,

       50,  372,   51,   51,   51,   51,   51,   51,  370,   58,
       56,  369,   55,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  173,   59,  365,  377,  377,   57,  377,
      377,  265,  377,  377,  377,  377,  267,   72,  364,  377,
      377,   60,  363,  377,  377,   78,  359,   62,  358,   61,
       65,   63,  130,   73,   68,  377,  377,   64,   69,   66,
      357,   79,   70,  356,   67,   74,   80,   81,  377,  377,
       43,   43,   43,   71,   75,   77,   43,   43,   44,   76,
       87,   87,   87,   87,  265,   83,   82,   84,   90,  267,
       49,   49,   49,   49,   49,   49,  377,  377,   94,   45,

       85,   91,   91,   91,   91,   91,   91,   92,   92,   92,
       92,   92,   92,   93,   93,   93,   93,   93,   93,  377,
      377,  377,  377,  351,  377,  377,  377,  377,   98,  377,
      377,  350,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  265,  377,
      377,  377,  377,  292,  377,  377,  377,  377,  349,  377,
      377,  114,  348,  377,  377,   96,   97,   95,  107,  377,
      377,  100,  347,  101,  343,   99,  102,  377,  377,  104,
      341,  103,  105,  106,  111,  377,  377,  108,  110,  377,
      377,  120,  109,  115,  340,  112,  116,  113,  377,  377,

      377,  377,  338,  377,  377,  377,  377,  377,  377,  337,
      117,  377,  377,  126,  377,  377,  336,  118,  377,  377,
      377,  377,  377,  377,  119,  129,  129,  129,  129,  129,
      129,  377,  377,  329,  121,  328,  125,  326,  377,  377,
      377,  377,  122,  123,  124,  132,  132,  132,  132,  132,
      132,   45,  147,   91,   91,   91,   91,   91,   91,  134,
      137,  127,  128,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  377,  377,  377,  377,  377,
      377,  157,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,

      377,  377,  377,  377,  377,  377,  325,  135,  138,  324,
      140,  377,  377,  312,  139,  308,  143,  136,  141,  307,
      146,  145,  144,  142,  377,  377,  148,  149,  152,  377,
      377,  377,  377,  377,  377,  377,  377,  150,  306,  154,
      377,  377,  151,  377,  377,  377,  377,  153,  377,  377,
      305,  155,  377,  377,  290,  156,  251,  377,  377,  252,
      377,  377,  253,  159,  161,  377,  377,  377,  377,  377,
      377,  160,  287,  158,  377,  377,  377,  377,  163,  162,
      283,  377,  377,  282,  166,  167,  377,  377,  377,  377,
      164,  168,  377,  377,  377,  377,  169,  165,  281,  170,

      172,  172,  172,  172,  172,  172,  132,  132,  132,  132,
      132,  132,  176,  177,  171,  377,  377,  280,  179,  178,
      377,  377,  377,  377,  181,  268,  182,  377,  377,  377,
      377,  377,  377,  377,  377,  180,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  254,  377,
      377,  238,  184,  207,  185,  377,  377,  187,  377,  377,
      377,  377,  206,  183,  377,  377,  189,  377,  377,  186,
      190,  175,  191,  192,  194,  188,  193,  195,  377,  377,
      377,  377,  174,  196,  377,  377,  377,  377,  377,  377,
      377,  377,  198,  377,  377,  377,  377,  377,  377,  377,

      377,  173,  197,  131,  377,  377,  208,  209,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      201,  130,  199,  377,  377,   89,  200,  203,  377,  377,
      377,  377,  377,  377,  377,  377,   88,  202,   86,  204,
      205,  377,  377,  377,  377,   53,  214,   52,  210,  377,
      377,  377,  211,  215,  377,  377,  377,  212,  377,  377,
      213,  377,  377,  216,  377,  377,  377,  377,  377,  377,
      217,  218,  219,  377,  377,  377,  377,  377,  377,  221,
      377,  377,  222,  377,  377,  377,  377,  377,  377,  220,
      377,  377,  377,  225,  377,  226,  377,  377,  377,  377,

      377,  377,  377,  223,  227,  377,  224,  236,  237,  239,
      239,  239,  239,  239,  377,  230,  377,  232,  228,  239,
      239,  239,  377,  377,  231,  229,  233,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  234,
      377,  377,  235,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  240,  377,
      377,  377,  377,  377,  377,  377,  377,  242,  377,  377,
      241,  377,  377,  245,  377,  246,  247,  377,  377,  243,
      377,  244,  250,  249,  377,  377,  248,  377,  377,  377,
      377,  264,  264,  264,  377,  255,  256,  377,  258,  259,

      264,  264,  264,  264,  264,  377,  257,  377,  377,  377,
      377,  377,  377,  377,  377,  262,  377,  377,  272,  377,
      377,  273,  377,  260,  377,  377,  261,  377,  377,  377,
      263,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  270,  377,  377,  377,  377,  377,  274,  269,  377,
      377,  377,  271,  377,  377,  275,  377,  377,  377,  377,
      265,  294,  295,  295,  296,  292,  377,  276,  377,  377,
      377,  377,  293,  277,  377,  278,  377,  377,  377,  284,
      279,  377,  377,  285,  377,  377,  377,  286,  377,  377,
      377,  288,  377,  377,  377,  377,  377,  377,  377,  377,

      289,  377,  377,  377,  377,  377,  377,  377,  377,  299,
      298,  377,  377,  377,  297,  377,  377,  377,  377,  315,
      316,  316,  317,  265,  300,  377,  302,  377,  292,  301,
      319,  319,  319,  319,  319,  293,  377,  303,  310,  311,
      265,  319,  319,  304,  309,  292,  318,  318,  318,  318,
      318,  318,  319,  319,  319,  319,  319,  319,  377,  377,
      313,  377,  377,  314,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  331,  331,  331,  331,  331,  331,
      331,  377,  377,  377,  321,  377,  377,  377,  377,  377,

      322,  377,  377,  377,  377,  320,  377,  377,  377,  377,
      330,  323,  331,  331,  331,  331,  331,  331,  377,  265,
      332,  377,  377,  327,  292,  318,  318,  318,  318,  318,
      318,  377,  377,  377,  377,  377,  333,  377,  377,  377,
      377,  334,  377,  377,  377,  377,  342,  335,  339,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  345,
      344,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  352,  377,  377,  377,  346,  377,  377,  354,  377,
      377,  377,  377,  377,  377,  377,  377,  362,  377,  377,
      377,  353,  360,  377,  355,  377,  377,  377,  361,  377,

      377,  377,  377,  377,  377,  377,  377,  366,  377,  367,
      368,  371,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  374,   45,  377,   45,  266,  266,
      291,  291,    3,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377
    } ;

static yyconst short int yy_chk[1189] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    5,    5,    6,    6,
        6,    7,    7,    7,    8,    8,    9,    9,    9,    9,
        9,    9,   10,   10,   11,   11,   11,   11,   11,   11,
       18,   18,   19,   19,   20,   20,   21,   21,  375,    9,
      372,    9,   13,   13,   26,   26,   31,   31,   18,  370,

       13,  369,   13,   13,   13,   13,   13,   13,  364,   21,
       19,  363,   18,   27,   27,   28,   28,   36,   36,   29,
       29,   32,   32,  174,   26,  359,   30,   30,   20,   33,
       33,  238,   34,   34,   35,   35,  238,   31,  358,   37,
       37,   27,  356,   38,   38,   36,  351,   28,  350,   27,
       29,   28,  174,   32,   30,   45,   45,   28,   30,   29,
      349,   36,   30,  347,   29,   33,   36,   37,   39,   39,
       43,   43,   43,   30,   34,   35,   44,   44,   44,   34,
       46,   46,   46,   46,  266,   38,   37,   38,   49,  266,
       49,   49,   49,   49,   49,   49,   54,   54,   54,   50,

       39,   50,   50,   50,   50,   50,   50,   52,   52,   52,
       52,   52,   52,   53,   53,   53,   53,   53,   53,   55,
       55,   56,   56,  341,   57,   57,   58,   58,   58,   59,
       59,  340,   60,   60,   61,   61,   62,   62,   63,   63,
       65,   65,   64,   64,   66,   66,   67,   67,  291,   68,
       68,   70,   70,  291,   69,   69,   71,   71,  338,   72,
       72,   72,  337,   73,   73,   56,   57,   55,   65,   74,
       74,   60,  336,   60,  331,   59,   60,   75,   75,   62,
      329,   61,   63,   64,   69,   76,   76,   66,   68,   77,
       77,   77,   67,   72,  328,   70,   73,   71,   78,   78,

       79,   79,  326,   80,   80,   81,   81,   82,   82,  325,
       74,   83,   83,   83,   84,   84,  324,   75,   85,   85,
      105,  105,   96,   96,   76,   87,   87,   87,   87,   87,
       87,   94,   94,  312,   78,  311,   82,  308,  114,  114,
      148,  148,   79,   80,   81,   90,   90,   90,   90,   90,
       90,   91,  105,   91,   91,   91,   91,   91,   91,   94,
       96,   84,   85,   92,   92,   92,   92,   92,   92,   93,
       93,   93,   93,   93,   93,   95,   95,   97,   97,   98,
       98,  114,   99,   99,  100,  100,  101,  101,  102,  102,
      103,  103,  104,  104,  106,  106,  107,  107,  108,  108,

      109,  109,  110,  110,  111,  111,  307,   95,   97,  305,
       98,  112,  112,  287,   97,  283,  101,   95,   99,  282,
      104,  103,  102,  100,  113,  113,  106,  107,  109,  115,
      115,  116,  116,  117,  117,  118,  118,  108,  281,  111,
      119,  119,  108,  120,  120,  121,  121,  110,  122,  122,
      280,  112,  123,  123,  264,  113,  225,  124,  124,  225,
      125,  125,  225,  116,  118,  126,  126,  127,  127,  128,
      128,  117,  258,  115,  135,  135,  136,  136,  120,  119,
      254,  134,  134,  253,  123,  124,  137,  137,  138,  138,
      121,  125,  139,  139,  140,  140,  126,  122,  252,  127,

      129,  129,  129,  129,  129,  129,  132,  132,  132,  132,
      132,  132,  134,  135,  128,  141,  141,  251,  137,  136,
      142,  142,  143,  143,  139,  239,  140,  144,  144,  145,
      145,  146,  146,  149,  149,  138,  147,  147,  150,  150,
      151,  151,  152,  152,  153,  153,  154,  154,  226,  155,
      155,  207,  142,  173,  143,  156,  156,  145,  157,  157,
      158,  158,  172,  141,  159,  159,  147,  160,  160,  144,
      150,  133,  151,  152,  154,  146,  153,  155,  161,  161,
      162,  162,  131,  156,  163,  163,  164,  164,  165,  165,
      166,  166,  158,  167,  167,  168,  168,  169,  169,  170,

      170,  130,  157,   89,  171,  171,  175,  175,  176,  176,
      177,  177,  178,  178,  179,  179,  180,  180,  182,  182,
      165,   88,  161,  181,  181,   48,  163,  168,  183,  183,
      184,  184,  185,  185,  186,  186,   47,  167,   42,  169,
      171,  187,  187,  188,  188,   15,  180,   14,  176,  189,
      189,    3,  177,  181,  190,  190,    0,  178,  191,  191,
      179,  193,  193,  182,  192,  192,  194,  194,  195,  195,
      183,  185,  187,    0,  196,  196,  197,  197,    0,  189,
      198,  198,  190,  199,  199,  200,  200,  201,  201,  188,
      202,  202,    0,  194,    0,  195,  203,  203,  204,  204,

      205,  205,    0,  191,  196,    0,  192,  206,  206,  208,
      208,  208,  208,  208,    0,  199,    0,  201,  197,  209,
      209,  209,  210,  210,  200,  198,  202,  211,  211,  212,
      212,  213,  213,  214,  214,  215,  215,  216,  216,  203,
      217,  217,  205,  218,  218,  219,  219,    0,  220,  220,
      221,  221,  222,  222,  223,  223,  224,  224,  210,  227,
      227,    0,  228,  228,  229,  229,    0,  213,  231,  231,
      211,  230,  230,  216,    0,  218,  220,  232,  232,  214,
        0,  215,  223,  222,  233,  233,  221,  234,  234,  235,
      235,  237,  237,  237,    0,  227,  228,    0,  230,  231,

      236,  236,  236,  236,  236,    0,  229,  240,  240,  241,
      241,  242,  242,  245,  245,  234,  243,  243,  243,  244,
      244,  244,    0,  232,  246,  246,  233,  247,  247,    0,
      235,  248,  248,  249,  249,  250,  250,  255,  255,  256,
      256,  241,  257,  257,  259,  259,    0,  245,  240,  260,
      260,    0,  242,  261,  261,  246,  262,  262,  263,  263,
      267,  268,  268,  268,  268,  267,    0,  247,  269,  269,
      270,  270,  267,  248,    0,  249,  271,  271,    0,  255,
      250,  272,  272,  256,  273,  273,    0,  257,  274,  274,
        0,  260,  275,  275,  276,  276,  277,  277,  278,  278,

      262,  279,  279,  284,  284,    0,  285,  285,    0,  272,
      271,    0,  286,  286,  270,  288,  288,  289,  289,  290,
      290,  290,  290,  292,  273,    0,  276,    0,  292,  274,
      294,  294,  294,  294,  294,  292,    0,  277,  285,  286,
      293,  296,  296,  278,  284,  293,  293,  293,  293,  293,
      293,  293,  295,  295,  295,  295,  295,  295,  297,  297,
      288,  298,  298,  289,  299,  299,  300,  300,  301,  301,
      302,  302,  303,  303,  304,  304,  309,  309,  310,  310,
      313,  313,  314,  314,  315,  315,  315,  315,  315,  317,
      317,    0,  320,  320,  300,  321,  321,  322,  322,    0,

      301,  323,  323,  327,  327,  299,  330,  330,  334,  334,
      314,  302,  316,  316,  316,  316,  316,  316,    0,  318,
      320,  332,  332,  310,  318,  318,  318,  318,  318,  318,
      318,  333,  333,  335,  335,    0,  321,  339,  339,  342,
      342,  322,  344,  344,  345,  345,  330,  323,  327,  346,
      346,  352,  352,  353,  353,  354,  354,  355,  355,  333,
      332,  360,  360,  361,  361,    0,  362,  362,    0,  366,
      366,  342,  367,  367,    0,  335,  368,  368,  345,  371,
      371,  374,  374,    0,    0,    0,    0,  354,    0,    0,
        0,  344,  352,    0,  346,    0,    0,    0,  353,    0,

        0,    0,    0,    0,    0,    0,    0,  360,    0,  361,
      362,  366,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  371,  378,    0,  378,  379,  379,
      380,  380,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#define INITIAL 0
/*definicciones*/
#line 3 "lex.l"
    #include "parser.tab.h"
    #include <string.h>
    #include <stdio.h>
    #include <stdlib.h>
    int yylex();
    extern void yyerror(const char *s); // Declaración externa de yyerror
    extern int yylex(); // Declaración externa de yylex

    extern int yychar; // Declaración externa de yychar
    extern YYSTYPE yylval; // Declaración externa de yylval
    extern int yynerrs; // Declaración externa de yynerrs
    int Nlinea = 1;
#line 763 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 25 "lex.l"

#line 916 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 378 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1133 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 26 "lex.l"
{Nlinea++;} 
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 27 "lex.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 28 "lex.l"
{return GuionBajo;} 
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 29 "lex.l"
{return guinmedio;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 30 "lex.l"
{return oacento;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 31 "lex.l"
{return Allave;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 32 "lex.l"
{return Cllave;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 33 "lex.l"
{return Acorchete;} 
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 34 "lex.l"
{return Ccorchete;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 35 "lex.l"
{return coma;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 36 "lex.l"
{return barra;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 37 "lex.l"
{return barrainvertida;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 38 "lex.l"
{yylval.real = atof(yytext); return real;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 39 "lex.l"
{yylval.entero = atoi(yytext); return entero;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 40 "lex.l"
{strcpy(yylval.boolean, yytext); return boolean ;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 41 "lex.l"
{strcpy(yylval.boolean, yytext); return boolean ;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 42 "lex.l"
{yylval.reservada = yytext; return inprogress;} 
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 43 "lex.l"
{yylval.reservada = yytext; return todo;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 44 "lex.l"
{yylval.reservada = yytext; return canceled;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 45 "lex.l"
{yylval.reservada = yytext; return done;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 46 "lex.l"
{yylval.reservada = yytext; return onhold;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 47 "lex.l"
{yylval.date = strdup(yytext);  return date;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 48 "lex.l"
{yylval.url = yytext; return url;} 
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 49 "lex.l"
{return dospuntos;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 50 "lex.l"
{return comillas ;}  
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 51 "lex.l"
{yylval.reservada = yytext; return empresas;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 52 "lex.l"
{yylval.reservada = yytext; return nombreEmpresa;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 53 "lex.l"
{yylval.reservada = yytext; return fundacion; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 54 "lex.l"
{yylval.reservada = yytext; return direccion;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 55 "lex.l"
{yylval.reservada = yytext; return calle;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 56 "lex.l"
{yylval.reservada = yytext; return ciudad;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 57 "lex.l"
{yylval.reservada = yytext; return pais;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 58 "lex.l"
{ yylval.reservada= yytext; return ingresosAnio;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 59 "lex.l"
{yylval.reservada= yytext; return pyme;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 60 "lex.l"
{yylval.reservada = yytext; return link;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 61 "lex.l"
{yylval.reservada = yytext; return deptos;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 62 "lex.l"
{yylval.reservada = yytext; return nombre;} 
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 63 "lex.l"
{yylval.reservada = yytext; return activo;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 64 "lex.l"
{yylval.reservada = yytext; return jefe;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 65 "lex.l"
{yylval.reservada =yytext; return subdeptos;} 
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 66 "lex.l"
{yylval.reservada=yytext; return empleados;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 67 "lex.l"
{yylval.reservada=yytext; return edad;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 68 "lex.l"
{yylval.reservada=yytext; return cargo;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 69 "lex.l"
{yylval.reservada=yytext; return PA;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 70 "lex.l"
{yylval.reservada=yytext; return PM;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 71 "lex.l"
{yylval.reservada=yytext; return UXD;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 72 "lex.l"
{yylval.reservada=yytext; return MK;}  
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 73 "lex.l"
{yylval.reservada=yytext; return DEV;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 74 "lex.l"
{yylval.reservada=yytext; return devops;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 75 "lex.l"
{yylval.reservada=yytext; return DBA;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 76 "lex.l"
{yylval.reservada= yytext; return salario;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 77 "lex.l"
{yylval.reservada= yytext; return fechacontrato;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 78 "lex.l"
{yylval.reservada = yytext; return proyectos;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 79 "lex.l"
{ yylval.reservada = yytext; return estado;} 
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 80 "lex.l"
{yylval.reservada = yytext; return fechaI;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 81 "lex.l"
{yylval.reservada =yytext; return fechaF;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 82 "lex.l"
{yylval.reservada=yytext; return version;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 83 "lex.l"
{yylval.reservada = yytext; return nulo;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 84 "lex.l"
{yylval.reservada=yytext; return firma_digital;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 85 "lex.l"
{sscanf (yytext, "%s", yylval.string); return string;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 86 "lex.l"
{printf ("error"); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 88 "lex.l"
{ printf("Es invalido el dato Date: %s \n", yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 90 "lex.l"
ECHO;
	YY_BREAK
#line 1314 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 378 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 378 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 377);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 90 "lex.l"

